title: It's MY awesome title
author: Tyler Sanbar
email: tylersanbar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I've got a site for you, one to cure your blues and destroy your craving for news.

# social links
twitter_username: your-twitter-handle
github_username: tylersanbar

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
